apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "immuta-mcp.fullname" . }}
  labels:
    {{- include "immuta-mcp.labels" . | nindent 4 }}
data:
  IMMUTA_BASE_URL: {{ .Values.immuta.baseUrl | quote }}
